name: Auto Sync

on:
  schedule:
    - cron: '0 8 * * 1' # Cek update setiap hari Senin jam 8 pagi
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Pull latest changes
      run: |
        git pull origin main

