name: Keep Alive

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Send dummy commit / ping
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git commit --allow-empty -m "Keep-alive: Refresh repository status"
        git push
